language: python
os: linux
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master

before_install:
  - ./continuous_integration/before_install.sh

install:
  - docker exec -it kerberosauthenticator-testing ./working/continuous_integration/install.sh

script:
  - docker exec -it kerberosauthenticator-testing ./working/continuous_integration/script.sh

notifications:
  email: false
